### PR TITLE
fix(ui/FloatingPanel): remove animation if no anchor when init

### LINKED ISSUE #1535: floating-panel 自定义锚点的时候没有向上的一个动画效果了
# Bug report 🐞
 floating-panel 自定义锚点的时候没有向上的一个过渡动画效果了，如果不使用自定义锚点就会有过渡动画
## Version & Environment
 "vite": "^4.4.5"
 "@varlet/ui": "^3.0.7",

### PR DESCRIPTION
**Pull request by wangKBweb**
## Checklist

List of tasks you have already done and plan to do.

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

fix FloatingPanel init bug

## Issues

close #1535

### CODE REVIEW

**Review by chouchouji — APPROVED** [review]

File: packages/varlet-ui/src/floating-panel/FloatingPanel.vue [hunk 1]
```diff
@@ -44,11 +44,11 @@ export default defineComponent({
   name,
   props,
   setup(props) {
-    const visibleHeight = ref<number>(0)
     const contentRef = ref<HTMLElement | null>(null)
     const { height: windowHeight } = useWindowSize()
     const defaultEndAnchor = computed(() => windowHeight.value * 0.6)
     const anchor = useVModel(props, 'anchor')
```
Comment (haoziqaq) [inline packages/varlet-ui/src/floating-panel/FloatingPanel.vue:50]: `const anchor = useVModel(props, 'anchor', { defaultValue: DEFAULT_START_ANCHOR })`

应该就可以了吧，其他的应该不用变。

Comment (wangKBweb) [reply packages/varlet-ui/src/floating-panel/FloatingPanel.vue:50]: 好吧...好像还真是
