### PR TITLE
fix(menu): don't compute hostSize when no host element

### LINKED ISSUE #1438: 使用 menuSelect组件 点击路由跳转报错
# Bug report 🐞

使用menuSelect组件 点击路由跳转报错

**原因**是点击离开选项会触发 `resize ` 函数，resize 会 触发  `computeHostSize` 函数，而此时 `host.value` 为 `null`

image

image

## Version & Environment

`
 "@varlet/touch-emulator": "latest",
 "@varlet/ui": "latest",
 "vue": "^3.3.4",
 "vue-router": "^4.2.5"
`

## Actual results (or Errors)

`const getStyle = (element) => window.getComputedStyle(element);`

image

image

## Reproduction link

[demo.zip](https://github.com/varletjs/varlet/files/14046070/demo.zip)

### PR DESCRIPTION
**Pull request by YHoney7**
## Checklist

List of tasks you have already done and plan to do.

- [ ] Fix linting errors
- [ ] Tests have been added / updated (or snapshots)

## Change information

Describe your modifications here.

## Issues

close #1438 

## Related Links

Links related to this pr.

### CODE REVIEW

File: packages/varlet-ui/src/menu/usePopover.ts [hunk 1]
```diff
@@ -75,6 +75,10 @@ export function usePopover(options: UsePopoverOptions) {
   let enterHost = false
 
   const computeHostSize = () => {
+    if (!host.value) {
+      return
+    }
+
     const { width, height } = getStyle(host.value!)
```
Comment (haoziqaq) [inline packages/varlet-ui/src/menu/usePopover.ts:82]: remove `!` of the `host.value`

Comment (YHoney7) [reply packages/varlet-ui/src/menu/usePopover.ts:82]: copy that

**Review by chouchouji — APPROVED** [review]
